package src;


import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Point;
import sun.java2d.loops.DrawPolygons;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Setty
 */
public class DrawPlane extends javax.swing.JPanel {

    /**
     * Creates new form DrawPlane
     */
    int triangleXPoints[];
    int triangleYPoints[];
    
    int triangleWidth;
    
    public DrawPlane() {
        this.triangleWidth = 200;
        initComponents();
        
        triangleXPoints = new int[4];
        triangleYPoints = new int[4];
        setBackground(Color.black);
    }
    
    @Override
    public void paint(Graphics g){
        super.paint(g);
        this.setBaseWidth();
        
        g.setColor(Color.GREEN);
        g.fillPolygon(triangleXPoints, triangleYPoints, 3);
    }
    
    private void setBaseWidth(){
        triangleXPoints[0] = 350;
        triangleYPoints[0] = 100;
        triangleYPoints[1] = 400;
        triangleYPoints[2] = 400;
        triangleXPoints[1] = triangleXPoints[0] - triangleWidth / 2;
        triangleXPoints[2] = triangleXPoints[0] + triangleWidth / 2;
    }
    
    public void setTriangleWidth(int value){
        triangleWidth = value;
       repaint();
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
